backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "galeria"
    label: "Galería"
    folder: "images"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Imagen", name: "image", widget: "image" }
      - { label: "Categoría", name: "categoria", widget: "select", options: ["Infantiles", "Juveniles", "Primera"] }
